application: llazzarohome
version: 1
runtime: python
api_version: 1

default_expiration: "5d 12h"

handlers:
- url: /blog/admin
  script: blog.py
  login: admin

- url: /blog/admin/.*
  script: blog.py
  login: admin

- url: /image
  script: index.py

- url: /contact
  script: index.py

- url: /static
  static_dir: static

- url: /doc
  static_dir: doc

- url: /static/img
  static_dir: /static/img

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /blog
  script: blog.py

- url: /blog/.*
  script: blog.py


- url: /projects
  script: projects.py

- url: /cv
  script: cv.py

- url: /cv/edit
  script: cv.py
  login: admin

- url: /photos
  script: photos.py

- url: /photos/.*
  script: photos.py

- url: /photos/admin
  script: photos.py
  login: admin

- url: /photos/admin/.*
  script: photos.py
  login: admin

- url: /portfolio
  script: portfolio.py

- url: /networks
  script: networks.py

- url: /networks/admin
  script: networks.py
  login: admin

- url: /networks/admin/.*
  script: networks.py
  login: admin

- url: /
  script: index.py

